version: "3.8"
services:
  flexo:
    build: .
    ports:
      - "127.0.0.1:8080:8080" # Change port?
    environment:
      DBADDR: "db:3306"
      DBUSER: flexo
      DBPASS: flexo
      DBNAME: flexo

      GIN_MODE: release
    depends_on:
      - db

  db: # Will be updated to a pg in issue #3
    image: mysql:5.7.14
    ports:
      - "127.0.0.1:3306:3306"
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes" # will be printed to stdout
      MYSQL_DATABASE: flexo
      MYSQL_USER: flexo
      MYSQL_PASSWORD: flexo #Change that
